core/api/urls.py
from django.urls import path

from .views import ItemListAPIView

app_name = 'api'


urlpatterns = [
    path('items/', ItemListAPIView.as_view(), name='items')
]

core/urls.py
from django.urls import path, include

from . import views
from .api.views import ItemListAPIView

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('shop', views.ShopView.as_view(), name='shop'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('about', views.AboutView.as_view(), name='about'),
    path('contact', views.ContactView.as_view(), name='contact'),
    path('cart', views.CartView.as_view(), name='cart'),
    path('add-to-favourites/<slug:slug>', views.add_to_favourites, name='add-to-favourites'),
    path('add-to-cart/<slug:slug>', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>', views.remove_from_cart, name='remove-from-cart'),
    path('order', views.order, name='order'),

    path('api/', include('core.api.urls'))
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from store.settings.settings import MEDIA_URL, MEDIA_ROOT, STATIC_URL, STATIC_ROOT

app_name = 'store'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile'),
]

core/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from django.conf import settings


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class ItemAttributeValue(BaseModel):
    value = models.CharField(max_length=200)

    def __str__(self):
        return self.value


class ItemAttribute(BaseModel):
    name = models.CharField(max_length=200)
    values = models.ManyToManyField(ItemAttributeValue)

    def __str__(self):
        return self.name


class Item(BaseModel):
    class ItemCategoryChoices(models.TextChoices):
        LAPTOPS = 'LA'
        COMPUTER_MICE = 'CM'
        WATCHES = 'WA'
        CPUS = 'CP'
        GPUS = 'GP'
        MONITORS = 'MO'

    objects = models.Manager()

    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.IntegerField(default=100)
    units_sold = models.BigIntegerField(default=0)
    units_in_stock = models.BigIntegerField(default=0)
    slug = models.SlugField(unique=True, blank=True, editable=False)
    main_image = models.ImageField(default='', upload_to='img/items/', blank=True)
    featured = models.BooleanField(default=False)

    attributes = models.ManyToManyField(ItemAttribute, blank=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('core:product', kwargs={
            'slug': self.slug
        })

    def get_attributes_key_value_pairs(self):
        attributes = dict()

        for attribute in self.attributes.all():
            breakpoint()

    def get_add_to_cart_url(self):
        return reverse('core:add-to-cart', kwargs={
            'slug': self.slug
        })

    def create_slug(self):
        return f'{slugify(self.name)}'

    def save(self, *args, **kwargs):
        self.slug = self.create_slug()
        super(Item, self).save(*args, **kwargs)


class OrderedItem(BaseModel):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.name}'


class Cart(BaseModel):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderedItem)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(default=None)

    def __str__(self):
        return f'{self.user}\'s cart'


class ItemCategory(BaseModel):
    class Meta:
        verbose_name_plural = 'Item categories'

    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=200, default='')
    name_lowercase = models.CharField(max_length=200, default='', blank=True)
    image = models.ImageField(default='', upload_to='img/', blank=True)
    items = models.ManyToManyField(Item)
    number_of_items = models.IntegerField(editable=False, default=0)

    def __str__(self):
        return f'{self.name} ({self.number_of_items} items)'

    def save(self, *args, **kwargs):
        self.name_lowercase = str(self.name).lower()
        super().save(*args, **kwargs)

core/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=256,
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        })
    )
    email = forms.EmailField(
        min_length=5,
        max_length=256,
        widget=forms.EmailInput(attrs={
            'class': 'form-control'
        })
    )
    subject = forms.CharField(
        max_length=256,
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        })
    )
    message = forms.CharField(
        max_length=2048,
        widget=forms.Textarea(attrs={
            'class': 'form-control'
        })
    )

core/api/views.py
from rest_framework.generics import ListAPIView

from core.models import Item
from .serializers import ItemSerializer


class ItemListAPIView(ListAPIView):
    model = Item
    queryset = model.objects.all()
    serializer_class = ItemSerializer

core/views.py
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.db.models import Q, QuerySet

from .models import Item, ItemCategory, Cart, OrderedItem, ItemAttribute, ItemAttributeValue
from .filters import ItemFilter
from .forms import ContactForm


class ShopView(ListView):
    model = Item
    queryset = model.objects.all()
    template_name = 'core/shop.html'
    context_object_name = 'items'
    paginate_by = 6

    filterset = None

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = ItemFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs.order_by('name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = self.filterset.form
        return context


class ItemDetailView(DetailView):
    model = Item
    template_name = 'core/product.html'
    context_object_name = 'item'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)

        return render(request, self.template_name, context)


class HomeView(ListView):
    model = Item
    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['featured_products'] = Item.objects.filter().order_by('-id')[:6]
        context['featured_categories'] = ItemCategory.objects.filter().order_by('-id')[:3]

        return context


class AboutView(TemplateView):
    model = None
    template_name = 'core/about.html'


class ContactView(FormView):
    template_name = 'core/contact.html'
    form_class = ContactForm
    success_url = '/'


class CartView(ListView):
    model = Cart
    template_name = 'core/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cart_qs = context['cart_list'][0]

        context['user'] = cart_qs.user
        context['items'] = cart_qs.items.all()

        # :(
        # context['date'] = cart_qs.date

        return context


def add_to_favourites(request, *args, **kwargs):
    http_referer_url = request.META['HTTP_REFERER']
    return redirect(http_referer_url)


def add_to_cart(request, slug):
    if not request.user.is_authenticated:
        return redirect('users:login')

    http_referer_url = request.META['HTTP_REFERER']

    item = get_object_or_404(Item, slug=slug)
    ordered_item, _ = OrderedItem.objects.get_or_create(item=item, user=request.user, ordered=False)
    cart_qs = Cart.objects.filter(user=request.user, ordered=False)

    if cart_qs.exists():
        cart = cart_qs[0]

        if cart.items.filter(item__slug=item.slug).exists():
            item.units_in_stock -= 1
            item.save()

            ordered_item.quantity += 1
            ordered_item.save()
        else:
            cart.items.add(ordered_item)
    else:
        ordered_date = timezone.now()
        cart = Cart.objects.create(user=request.user, ordered_date=ordered_date)
        cart.items.add(ordered_item)

        item.units_in_stock -= 1

    return redirect(http_referer_url)


def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    ordered_item, created = OrderedItem.objects.get_or_create(item=item, user=request.user, ordered=False)
    cart_qs = Cart.objects.filter(user=request.user, ordered=False)

    if cart_qs.exists():
        cart = cart_qs[0]
        if cart.items.filter(item__slug=item.slug).exists():
            if ordered_item.quantity >= 2:
                ordered_item.quantity -= 1
                ordered_item.save()
            else:
                cart.items.remove(ordered_item)

            item.units_in_stock += 1

    return redirect('core:cart')


def order(request):
    order_status = True
    return render(request, 'core/order.html', context={
        'order_status': order_status
    })

core/templates/core/about.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block content %}

<div aria-hidden="true"
     aria-labelledby="exampleModalLabel"
     class="modal fade bg-white"
     id="templatemo_search"
     role="dialog"
     tabindex="-1">
    <div class="modal-dialog modal-lg" role="document">
        <div class="w-100 pt-1 mb-5 text-right">
            <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button"></button>
        </div>
        <form action="" class="modal-content modal-body border-0 p-0" method="get">
            <div class="input-group mb-2">
                <input class="form-control" id="inputModalSearch" name="q" placeholder="Search ..." type="text">
                <button class="input-group-text bg-success text-light" type="submit">
                    <i class="fa fa-fw fa-search text-white"></i>
                </button>
            </div>
        </form>
    </div>
</div>


<section class="bg-success py-5">
    <div class="container">
        <div class="row align-items-center py-5">
            <div class="col-md-8 text-white">
                <h1>About Us</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                </p>
            </div>
            <div class="col-md-4">
                <img alt="About Hero" src="{% static 'core/img/about-hero.svg' %}">
            </div>
        </div>
    </div>
</section>
<!-- Close Banner -->

<!-- Start Section -->
<section class="container py-5">
    <div class="row text-center pt-5 pb-3">
        <div class="col-lg-6 m-auto">
            <h1 class="h1">Our Services</h1>
        </div>
    </div>
    <div class="row">

        <div class="col-md-6 col-lg-3 pb-5">
            <div class="h-100 py-5 services-icon-wap shadow">
                <div class="h1 text-success text-center"><i class="fa fa-truck fa-lg"></i></div>
                <h2 class="h5 mt-4 text-center">Delivery Services</h2>
            </div>
        </div>

        <div class="col-md-6 col-lg-3 pb-5">
            <div class="h-100 py-5 services-icon-wap shadow">
                <div class="h1 text-success text-center"><i class="fas fa-exchange-alt"></i></div>
                <h2 class="h5 mt-4 text-center">Shipping & Return</h2>
            </div>
        </div>

        <div class="col-md-6 col-lg-3 pb-5">
            <div class="h-100 py-5 services-icon-wap shadow">
                <div class="h1 text-success text-center"><i class="fa fa-percent"></i></div>
                <h2 class="h5 mt-4 text-center">Promotion</h2>
            </div>
        </div>

        <div class="col-md-6 col-lg-3 pb-5">
            <div class="h-100 py-5 services-icon-wap shadow">
                <div class="h1 text-success text-center"><i class="fa fa-user"></i></div>
                <h2 class="h5 mt-4 text-center">24 Hours Service</h2>
            </div>
        </div>
    </div>
</section>
{% endblock %}

core/templates/core/cart.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Cart{% endblock %}

{% block content %}

{% for ordered_item in items %}
<section class="container py-5" style="padding-top: 0.5rem!important;padding-bottom: 0 !important">
    <div class="row">
        <div class="col-12 col-md-4 mb-4" style="margin-bottom: 0.5rem!important;">
            <div class="card h-100">
                <div class="card-body">
                    <ul class="list-unstyled d-flex justify-content-between">
                        <img class="rounded-circle img-thumbnail border" src="{{ ordered_item.item.main_image.url }}">
                        <li class="text-green text-right" style="color:green">${{ ordered_item.item.price }}</li>
                        <li>
                            <a class="btn btn-success text-white"
                               href="{% url 'core:remove-from-cart' slug=ordered_item.item.slug %}">
                                <i>X</i>
                            </a>
                        </li>

                    </ul>
                    <a href="{% url 'core:product' slug=ordered_item.item.slug %}"
                       style="font-weight: 400 !important; text-decoration: none;">{{ ordered_item.item.name }}</a>
                    <a class="text-green text-right"
                       style="color:red; margin-left: auto; margin-right: 0; text-decoration:none;">x{{ ordered_item.quantity }}</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endfor %}

<div>
    {% if items %}
    <a class="order-button" href="{% url 'core:order' %}">Order</a>
    {% else %}
    <p class="order-button disabled-button">Order</p>
    {% endif %}
</div>
{% endblock %}

core/templates/core/footer.html
<footer class="bg-dark" id="tempaltemo_footer">
    <div class="container">
        <div class="row">

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-success border-bottom pb-3 border-light logo">ExpensiveTrash</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                        123 Consectetur at ligula 10660
                    </li>
                    <li>
                        <i class="fa fa-phone fa-fw"></i>
                        <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                    </li>
                    <li>
                        <i class="fa fa-envelope fa-fw"></i>
                        <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4 pt-5">
                <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li><a class="text-decoration-none" href="{% url 'core:home' %}">Home</a></li>
                    <li><a class="text-decoration-none" href="{% url 'core:about' %}">About Us</a></li>
                    <li><a class="text-decoration-none" href="{% url 'core:contact' %}">Contact</a></li>
                </ul>
            </div>

        </div>
    </div>
</footer>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

<!-- Start Categories of The Month -->
<section class="container py-5">
    <div class="row text-center pt-3">
        <div class="col-lg-6 m-auto">
            <h1 class="h1">Categories of The Month</h1>
            <p>
                Check these out!
            </p>
        </div>
    </div>
    <div class="row">
        {% for category in featured_categories %}
        <div class="col-12 col-md-4 p-5 mt-3">
            <a href="{% url 'core:shop' %}?category={{ category.id }}">
                {% if category.image %}
                <img class="rounded-circle img-thumbnail border" src="{{ category.image.url }}">
                {% endif %}
            </a>
            <h5 class="text-center mt-3 mb-3">{{ category.name }}</h5>
            <p class="text-center">
                <a class="btn btn-success" href="{% url 'core:shop' %}?category={{ category.id }}">
                    Go Shop
                </a>
            </p>
        </div>
        {% endfor %}
    </div>
</section>
<!-- End Categories of The Month -->


<!-- Start Featured Product -->
<section class="bg-light">
    <div class="container py-5">
        <div class="row text-center py-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">Featured Products</h1>
            </div>
        </div>
        <div class="row">
            {% for item in featured_products %}
            <div class="col-12 col-md-4 mb-4">
                <div class="card h-100">
                    <a href="{% url 'core:product' slug=item.slug %}">
                        <img alt="..." class="card-img-top" src="{{ item.main_image.url }}">
                    </a>
                    <div class="card-body">
                        <ul class="list-unstyled d-flex justify-content-between">
                            <li class="text-green text-right">${{ item.price }}</li>
                        </ul>
                        <a class="h2 text-decoration-none text-dark"
                           href="{% url 'core:product' slug=item.slug %}">
                            {{ item.name }}
                        </a>
                        <p class="card-text">
                            {{ item.description }}
                        </p>
                        <p class="text-muted"></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- End Featured Product -->
{% endblock %}

core/templates/core/navbar.html
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
    <div class="container text-light">
        <div class="w-100 d-flex justify-content-between">
            <div>
                <i class="fa fa-envelope mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                <i class="fa fa-phone mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
            </div>
            <div>
                <a class="text-light" href="https://fb.com/templatemo" rel="sponsored" target="_blank"><i
                        class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.instagram.com/" target="_blank"><i
                        class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://twitter.com/" target="_blank"><i
                        class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i
                        class="fab fa-linkedin fa-sm fa-fw"></i></a>
            </div>
        </div>
    </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-light shadow">
    <div class="container d-flex justify-content-between align-items-center">

        <a class="navbar-brand text-success logo h1 align-self-center" href="{% url 'core:home' %}">
            ExpensiveTrash
        </a>

        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler border-0" data-bs-target="#templatemo_main_nav" data-bs-toggle="collapse"
                type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:shop' %}">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:about' %}">About</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar align-self-center d-flex">
                    <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                        <div class="input-group">
                            <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                            <div class="input-group-text">
                                <i class="fa fa-fw fa-search"></i>
                            </div>
                        </div>
                    </div>
                    <a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">
                        <i class="fa fa-fw fa-search text-dark mx-5"></i>
                    </a>
                    {% if request.user.is_authenticated %}
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'core:cart' %}">
                        <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">{{ request.user|card_item_count }}</span>
                    </a>
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:profile' user_id=user.id %}">
                        <i class="fa fa-fw fa-user text-dark mr-3"></i>
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark"></span>
                    </a>
                    {% else %}
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:login' %}">
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark ml-5">Login</span>
                    </a>
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:signup' %}">
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark mx-5">Sign up</span>
                    </a>
                    {% endif %}

            </div>
        </div>
    </div>
</nav>

<div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade bg-white" id="templatemo_search"
     role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg" role="document">
        <div class="w-100 pt-1 mb-5 text-right">
            <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button"></button>
        </div>
        <form action="{% url 'core:shop' %}" class="modal-content modal-body border-0 p-0" method="GET">
            <div class="input-group mb-2">
                <input class="form-control" id="inputModalSearch" name="name" placeholder="Search ..." type="text">
                <button class="input-group-text bg-success text-light" type="submit">
                    <i class="fa fa-fw fa-search text-white"></i>
                </button>
            </div>
        </form>
    </div>
</div>

core/templates/core/order.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Order{% endblock %}

{% block content %}

<div class="order-status">
    {% if order_status %}
    <h1>Items have been successfully ordered!</h1>
    {% else %}
    <h1>Oops! Something wrong happened! Order has not been finished!</h1>
    {% endif %}
</div>

{% endblock %}

core/templates/core/shop.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Shop{% endblock %}

{% block content %}

<!-- Start Content -->
<div class="container py-5">
    <div class="row">
        <!-- Filter form -->
        <div class="col-lg-3">
            <h1 class="h2 pb-3">Filter</h1>
            <div class="form-inline">
                <form action="{% url 'core:shop' %}" method="GET">
                    <i class="fas fa-cat"></i>
                    <div class="mb-3">
                        {{ filter_form.category }}
                    </div>

                    <i class="fa fas fa-signature"></i>
                    <div class="mb-3">
                        {{ filter_form.name }}
                    </div>

                    <i class="fa fa-solid fa-dollar-sign"></i>
                    <div class="mb-3">
                        {{ filter_form.price }}
                    </div>


                    <button class="btn btn-success mt-1" type="submit" value="Submit">Apply filters</button>
                    <button class="btn btn-danger mt-1">
                        <a class="text-reset text-decoration-none" href="/shop">Clear filters</a>
                    </button>
                </form>
            </div>
        </div>
        <!-- Filter form end -->


        <div class="col-lg-9">
            <div class="row">
                <div class="col-md-6 pb-4">
                    <div class="d-flex">
                        <select class="form-control">
                            <option value="featured">Featured</option>
                            <option value="atoz">A to Z</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for item in items %}
                <!-- Item -->
                <div class="col-md-4">
                    <div class="card mb-4 product-wap rounded-0">
                        <div class="card rounded-0">
                            <img class="card-img rounded-0 img-fluid" src="{{ item.main_image.url }}">
                            <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                <ul class="list-unstyled" id="item-card-menu">
                                    <!-- Add to favourites -->
                                    <li>
                                        <a class="btn btn-success text-white"

                                           href="{% url 'core:add-to-favourites' slug=item.slug %}">
                                            <i class="far fa-heart"></i>
                                        </a>
                                    </li>
                                    <!-- Go to the product page -->
                                    <li>
                                        <a class="btn btn-success text-white mt-2"
                                           href="{% url 'core:product' slug=item.slug %}">
                                            <i class="far fa-eye"></i>
                                        </a>
                                    </li>
                                    <!-- Add to cart -->
                                    <li>
                                        <a class="btn btn-success text-white mt-2"
                                           href="{% url 'core:add-to-cart' slug=item.slug %}">
                                            <i class="fas fa-cart-plus"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body">
                            <a class="h3 text-decoration-none" href="">{{ item.name }}</a>
                            <p class="text-center mb-0">${{ item.price }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% if is_paginated %}
            <div div="row">
                <ul class="pagination pagination-lg justify-content-end">
                    {% for page in page_obj.paginator %}
                    {% if page.number == page_obj.number %}
                    <li class="page-item disabled">
                        <a
                                class="page-link active rounded-0 mr-3 shadow-sm border-top-0 border-left-0"
                                href="?category={{ category.name_lowercase }}&page={{ page.number }}"
                                tabindex="-1">{{ page.number }}
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a
                                class="page-link intive rounded-0 mr-3 shadow-sm border-top-0 border-left-0"
                                href="?category={{ category.name_lowercase }}&page={{ page.number }}"
                                tabindex="-1">{{ page.number }}
                        </a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>

    </div>
</div>
<!-- End Content -->

{% endblock %}